# Generated by Django 5.1.4 on 2024-12-24 00:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatPoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255)),
                ('player_num', models.CharField(max_length=255)),
                ('player_img', models.CharField(max_length=255)),
                ('game_id', models.CharField(max_length=255)),
                ('game_datetime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('stat_id', models.CharField(max_length=50)),
                ('stat_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statpools.statpool')),
            ],
        ),
        migrations.CreateModel(
            name='StatPoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('stat_pool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statpools.statpool')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatPoolUserPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.FloatField(default=0.0)),
                ('stat_pool_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statpools.statpoolcategory')),
                ('stat_pool_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statpools.statpooluser')),
            ],
        ),
    ]
