# Generated by Django 5.1.4 on 2024-12-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statpooluserpick',
            old_name='stat_pool_category_id',
            new_name='stat_pool_category',
        ),
        migrations.RenameField(
            model_name='statpooluserpick',
            old_name='stat_pool_user_id',
            new_name='stat_pool_user',
        ),
        migrations.RenameField(
            model_name='statpooluserpick',
            old_name='pick',
            new_name='value',
        ),
    ]
