# Generated by Django 5.1.4 on 2025-01-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0002_rename_stat_pool_category_id_statpooluserpick_stat_pool_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statpoolcategory',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
