# Generated by Django 5.1.4 on 2025-01-03 01:39

from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule

def create_instance(apps, schema_editor):
    # Create the instance
    interval = IntervalSchedule.objects.create(
        every=60, 
        period=IntervalSchedule.SECONDS
    )
    PeriodicTask.objects.create(
        interval=interval,
        name="stat-pools-score",
        task="statpools.tasks.score_games_task"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0004_statpoolcategory_value'),
    ]

    operations = [
        migrations.RunPython(create_instance)
    ]
