# Generated by Django 5.1.4 on 2025-01-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0005_add_score_games_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statpoolcategory',
            old_name='player_img',
            new_name='player_ref',
        ),
        migrations.RemoveField(
            model_name='statpoolcategory',
            name='player_num',
        ),
    ]
