# Generated by Django 5.1.4 on 2025-01-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0006_rename_player_img_statpoolcategory_player_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statpoolcategory',
            name='game_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
