# Generated by Django 5.1.4 on 2025-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0007_statpoolcategory_game_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='statpoolcategory',
            name='game_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
