# Generated by Django 5.1.4 on 2025-01-03 01:39

from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule

def create_instance(apps, schema_editor):
    # Create the instance
    interval = IntervalSchedule.objects.create(
        every=2, 
        period=IntervalSchedule.MINUTES
    )
    PeriodicTask.objects.create(
        interval=interval,
        name="update-stat-pools-status",
        task="statpools.tasks.update_stat_pools_status"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0008_statpoolcategory_game_status'),
    ]

    operations = [
        migrations.RunPython(create_instance)
    ]
