# Generated by Django 5.1.4 on 2025-01-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statpools', '0009_add_update_pools_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='statpool',
            name='status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
