LOGO = {
    'ARIZONA CARDINALS':'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png',
    'ATLANTA FALCONS':'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png',
    'BALTIMORE RAVENS':'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png',
    'BUFFALO BILLS':'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png',
    'CAROLINA PANTHERS':'https://a.espncdn.com/i/teamlogos/nfl/500/car.png',
    'CHICAGO BEARS':'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png',
    'CINCINNATI BENGALS':'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png',
    'CLEVELAND BROWNS':'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png',
    'DALLAS COWBOYS':'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png',
    'DENVER BRONCOS':'https://a.espncdn.com/i/teamlogos/nfl/500/den.png',
    'DETROIT LIONS':'https://a.espncdn.com/i/teamlogos/nfl/500/det.png',
    'GREEN BAY PACKERS':'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png',
    'HOUSTON TEXANS':'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png',
    'INDIANAPOLIS COLTS':'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png',
    'JACKSONVILLE JAGUARS':'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png',
    'KANSAS CITY CHIEFS':'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
    'LAS VEGAS RAIDERS':'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png',
    'LOS ANGELES CHARGERS':'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png',
    'LOS ANGELES RAMS':'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png',
    'MIAMI DOLPHINS':'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png',
    'MINNESOTA VIKINGS':'https://a.espncdn.com/i/teamlogos/nfl/500/min.png',
    'NEW ENGLAND PATRIOTS':'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png',
    'NEW ORLEANS SAINTS':'https://a.espncdn.com/i/teamlogos/nfl/500/no.png',
    'NEW YORK GIANTS':'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png',
    'NEW YORK JETS':'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png',
    'PHILADELPHIA EAGLES':'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png',
    'PITTSBURGH STEELERS':'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png',
    'SAN FRANCISCO 49ERS':'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png',
    'SEATTLE SEAHAWKS':'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png',
    'TAMPA BAY BUCCANEERS':'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png',
    'TENNESSEE TITANS':'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png',
    'WASHINGTON COMMANDERS':'https://a.espncdn.com/i/teamlogos/nfl/500/was.png'
}

NAME = {
    'ARI':'ARIZONA CARDINALS',
    'ATL':'ATLANTA FALCONS',
    'BAL':'BALTIMORE RAVENS',
    'BUF':'BUFFALO BILLS',
    'CAR':'CAROLINA PANTHERS',
    'CHI':'CHICAGO BEARS',
    'CIN':'CINCINNATI BENGALS',
    'CLE':'CLEVELAND BROWNS',
    'DAL':'DALLAS COWBOYS',
    'DEN':'DENVER BRONCOS',
    'DET':'DETROIT LIONS',
    'GB':'GREEN BAY PACKERS',
    'GBP':'GREEN BAY PACKERS',
    'HOU':'HOUSTON TEXANS',
    'IND':'INDIANAPOLIS COLTS',
    'JAX':'JACKSONVILLE JAGUARS',
    'JAC':'JACKSONVILLE JAGUARS',
    'KC':'KANSAS CITY CHIEFS',
    'KCC':'KANSAS CITY CHIEFS',
    'LV':'LAS VEGAS RAIDERS',
    'LVR':'LAS VEGAS RAIDERS',
    'LAC':'LOS ANGELES CHARGERS',
    'LA':'LOS ANGELES RAMS',
    'LAR':'LOS ANGELES RAMS',
    'MIA':'MIAMI DOLPHINS',
    'MIN':'MINNESOTA VIKINGS',
    'NE':'NEW ENGLAND PATRIOTS',
    'NEP':'NEW ENGLAND PATRIOTS',
    'NO':'NEW ORLEANS SAINTS',
    'NOS':'NEW ORLEANS SAINTS',
    'NYG':'NEW YORK GIANTS',
    'NYJ':'NEW YORK JETS',
    'PHI':'PHILADELPHIA EAGLES',
    'PIT':'PITTSBURGH STEELERS',
    'SF':'SAN FRANCISCO 49ERS',
    'SFO':'SAN FRANCISCO 49ERS',
    'SEA':'SEATTLE SEAHAWKS',
    'TB':'TAMPA BAY BUCCANEERS',
    'TBB':'TAMPA BAY BUCCANEERS',
    'TEN':'TENNESSEE TITANS',
    'WAS':'WASHINGTON COMMANDERS',
    'WSH':'WASHINGTON COMMANDERS'
}

ID = {
    '1':'ATLANTA FALCONS',
    '2':'BUFFALO BILLS',
    '3':'CHICAGO BEARS',
    '4':'CINCINNATI BENGALS',
    '5':'CLEVELAND BROWNS',
    '6':'DALLAS COWBOYS',
    '7':'DENVER BRONCOS',
    '8':'DETROIT LIONS',
    '9':'GREEN BAY PACKERS',
    '10':'TENNESSEE TITANS',
    '11':'INDIANAPOLIS COLTS',
    '12':'KANSAS CITY CHIEFS',
    '13':'LAS VEGAS RAIDERS',
    '14':'LOS ANGELES RAMS',
    '15':'MIAMI DOLPHINS',
    '16':'MINNESOTA VIKINGS',
    '17':'NEW ENGLAND PATRIOTS',
    '18':'NEW ORLEANS SAINTS',
    '19':'NEW YORK GIANTS',
    '20':'NEW YORK JETS',
    '21':'PHILADELPHIA EAGLES',
    '22':'ARIZONA CARDINALS',
    '23':'PITTSBURGH STEELERS',
    '24':'LOS ANGELES CHARGERS',
    '25':'SAN FRANCISCO 49ERS',
    '26':'SEATTLE SEAHAWKS',
    '27':'TAMPA BAY BUCCANEERS',
    '28':'WASHINGTON COMMANDERS',
    '29':'CAROLINA PANTHERS',
    '30':'JACKSONVILLE JAGUARS',
    '33':'BALTIMORE RAVENS',
    '34':'HOUSTAN TEXANS'
}

STATS = [
    {'key':'completions', 'desc':'Completions', 'idx':1, 'positions':['QB']}, 
    {'key':'passingYards', 'desc':'Passing Yards', 'idx':1, 'positions':['QB']},
    {'key':'passingTouchdowns', 'desc':'Passing Touchdowns', 'idx':1, 'positions':['QB']},
    {'key':'longPassing', 'desc':'Longest Pass', 'idx':1, 'positions':['QB']},
    {'key':'interceptions', 'desc':'Interceptions', 'idx':1, 'positions':['QB']}, 
    {'key':'sacks', 'desc':'Sacks', 'idx':1, 'positions':['QB']},
    {'key':'longRushing', 'desc':'Longest Run', 'idx':2, 'positions':['QB','RB']},
    {'key':'rushingAttempts', 'desc':'Rushing Attempts', 'idx':2, 'positions':['QB','RB']},
    {'key':'rushingYards', 'desc':'Rushing Yards', 'idx':2, 'positions':['QB','RB']},
    {'key':'rushingTouchdowns', 'desc':'Rushing Touchdowns', 'idx':2, 'positions':['QB','RB']}, 
    {'key':'longReception', 'desc':'Longest Catch', 'idx':3, 'positions':['RB','WR','TE']},
    {'key':'receptions', 'desc':'Receptions', 'idx':3, 'positions':['RB','WR','TE']},
    {'key':'receivingTargets', 'desc':'Targets', 'idx':3, 'positions':['RB','WR','TE']},
    {'key':'receivingYards', 'desc':'Receiving Yards', 'idx':3, 'positions':['RB','WR','TE']},
    {'key':'receivingTouchdowns', 'desc':'Receiving Touchdowns', 'idx':3, 'positions':['RB','WR','TE']},
    {'key':'fieldGoalAttemptYards', 'desc':'Attempted Field Goal Yards', 'idx':5, 'positions':['K']},
    {'key':'fieldGoalsMade', 'desc':'Made Field Goals', 'idx':5, 'positions':['K']},
    {'key':'fieldGoalMadeYards', 'desc':'Made Field Goal Yards', 'idx':5, 'positions':['K']},
    {'key':'longFieldGoalMade', 'desc':'Longest Field Goal', 'idx':5, 'positions':['K']},
    {'key':'totalKickingPoints', 'desc':'Total Kicking Points', 'idx':5, 'positions':['K']},
]